### ISSUE TITLE
Multicore is lost after first event

### ISSUE THREAD

**Issue by blinkseb** [MoMEMta/MoMEMta#154]
When using the same instance of MoMEMta to run over many events, multicore is lost after the first event. Maybe indirectly related to #145 ?

**Comment by swertz** [comment]
That's weird, with #145 the memory is only freed when the process running MoMEMta ends, so it shouldn't have any impact. Have you tried reverting the PR? It's only one line to change...

**Comment by blinkseb** [comment]
Did not try anything for the moment, this will have to wait a bit :)

**Comment by blinkseb** [comment]
Reverting #145 solves the issue, multicore is still used after the first event

**Comment by blinkseb** [comment]
Maybe I spoke too soon, they seems to have some weird things going on, I now lost multi core later

**Comment by blinkseb** [comment]
Ok sorry for the noise, I had an infinite loop in my code firing at the 7th event. So I confirm that reverting #145 solves the issue, but I'm not sure why. Maybe when the forked processes exit the shared memory are destroyed and there's an error when trying to recreate? Anyway I'll need some time to debug this but it's a bit problematic...

**Comment by swertz** [comment]
As discussed, I cannot reproduce this!

**Comment by blinkseb** [comment]
Looks like I'm not able to reproduce it either...
