### ISSUE TITLE
Host travis build dependencies on a more reliable place

### ISSUE THREAD

**Issue by blinkseb** [MoMEMta/MoMEMta#159]
Currently, all build dependencies used by Travis (ROOT, LHAPDF, cmake, doxygen, ...) are hosted on my own CERN public space, which is unfortunately not so reliable. We need a better place to host these files. Best would be to have a dedicated storage space at CP3 from which we can store and download the files needed. @delaere, do you think such thing is possible?

**Comment by delaere** [comment]
Could you send me a tar with all these files, just to be sure not to forget one?

**Comment by delaere** [comment]
https://cp3-git.irmp.ucl.ac.be/cp3-support/helpdesk/issues/1591

**Comment by delaere** [comment]
Conclusion from that thread: let's use my cernbox.

**Comment by swertz** [comment]
Closed by #173
