### ISSUE TITLE
Make the 'MoMEMta::integrand' function public

### ISSUE THREAD

**Issue by swertz** [MoMEMta/MoMEMta#161]
In principle nothing prevents from making https://github.com/MoMEMta/MoMEMta/blob/master/core/src/MoMEMta.cc#L409 public. 

This would allows users to call the integrand configured using the whole machinery and the available modules, but do custom things such as using alternate integration algorithms, or something else entirely.

I don't see why it shouldn't work -> to be quickly tested some time.

**Comment by delaere** [comment]
We can close this, right?

**Comment by swertz** [comment]
Right, I thought it would be automatic through the reference from the PR...
