### ISSUE TITLE
Define versioning strategy

### ISSUE THREAD

**Issue by swertz** [MoMEMta/MoMEMta#24]
With @blinkseb's latests additions to the core of the code, I think we are becoming closer to rename the "prototype" main branch and define a first tag.

This also means defining the versioning scheme... Any ideas?

**Comment by blinkseb** [comment]
I really like the following model: https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/

**Comment by swertz** [comment]
This is what we're already doing, right? I was more wondering about deciding when to tag a version, and how to number them...

**Comment by blinkseb** [comment]
More or less yes. For versioning, there's this guide is found nice: http://semver.org/

We basically starts at version 0.1.0, and increment the minor version each time we *release* new functionality. Once we consider it's stable enough for physics (it means a proper exporter for Madgraph, documentation and working examples), then we bump to version 1.0.0.

We should also create milestone in github to track issues and PR and assign them to a specific release. For the moment it's probably not needed, but if we go public, we may have some feedback we'll have to properly classified and handle.

We also need some kind of rough roadmap for the future, at least with major features we want. No need for it to be detailed I think.

**Comment by swertz** [comment]
I think we can close this, we have more or less agreed on the rules.
