### ISSUE TITLE
Write module documentation

### ISSUE THREAD

**Issue by swertz** [MoMEMta/MoMEMta#38]
- [x] BinnedTransferFunctionOnEnergy
- [x] BlockB
- [x] BlockD -> Sebastien W
- [x] BlockF
- [x] Boost -> Miguel
- [x] BreitWignerGenerator -> Sebastien W
- [x] FlatTransferFunctionOnP
- [x] FlatTransferFunctionOnPhi
- [x] FlatTransferFunctionOnTheta
- [x] GaussianTransferFunction -> Miguel
- [x] MatrixElement
- [x] NarrowWidthApproximation
- [x] Permutator
- [x] UniformGenerator

**Comment by vidalm** [comment]
In the case of the ME module, I guess we should start with a draft and iterate from that.

**Comment by swertz** [comment]
Closing this since all the current modules are documented. From now on, I suggest we enforce new modules must be documented from the start.
