### ISSUE TITLE
Use tables to describes modules inputs / outputs instead of lists

### ISSUE THREAD

**Issue by blinkseb** [MoMEMta/MoMEMta#44]
This is a open questions. I tried to change the documention for Block F using tables instead of lists. IMO it makes the documentation clearer:

 - Before: [With list](http://momemta.github.io/MoMEMta/classBlockF.html)
 - After: ![With table](https://cloud.githubusercontent.com/assets/386274/15148428/898ad89a-16c5-11e6-8ca9-027dbee61660.png)

**Comment by swertz** [comment]
:+1:
