### ISSUE TITLE
BreitWignerGenerator uses float instead of double

### ISSUE THREAD

**Issue by blinkseb** [MoMEMta/MoMEMta#75]
While working on implementing the `Value` class, I saw that the `BreitWignerGenerator` class store the mass and the width as float instead of double.

While it should not change nothing theoretically, the integration of the ttbar sample is almost twice faster when using double instead of float (49177ms vs 28227ms).

I open this issue merely to remember to switch to double at some point.

**Comment by swertz** [comment]
Holy cow! Good catch! Do you understand why this has such a large impact??

**Comment by blinkseb** [comment]
I don't have a clear idea yet, but it seems the integration converges more quickly using double than float, but I don't know why. I'm wondering if the same observation hold for the WW sample?

**Comment by swertz** [comment]
I've tried it and get a smaller difference (21s versus 28s).

What's even more strange is that I get a small difference in the result (3.98e-21 versus 4.02e-21).

**Comment by blinkseb** [comment]
Interesting! Just tried it again, and I have 22s vs 38s, probably just because I test on my laptop and not on ingrid?

Also, something very unfortunate, I don't have the same result as you: 3.97973e-21 vs 3.98461e-21 (at least reproducible...), there's something fishy going on here...

**Comment by swertz** [comment]
Ok I've looked a bit more into it...

I have run by swichting one of the flatters to 'float' at a time, setting the others to 'double'. The results (solutions, integrand) are compatible to 5 to 7 significant digits depending on the PS point, which makes sense. Doing the same thing with all the flatters together, computing the integrand on the same PS point during the loop with either double or float, also there the integrands are equal to about 5-6 digits (a few exceptions though).

So the computation of the integrand itself seems quite fine. It looks like it might be a small difference in the way the grid is updated at each iteration by Vegas, that propagates to give a final result that is different (but still compatible within uncertainties btw). I don't know if it's worrying or expected!

As a check, I've run the computation using 'double', and saved the grid to a file. Then, I've run the computation using float and double, both times restoring the state file and looking only at the very first iteration (when the grid is not modified yet). Both gave the same integral at 6 significant digits.
