### ISSUE TITLE
Summer module does not reset its counter at the right moment

### ISSUE THREAD

**Issue by blinkseb** [MoMEMta/MoMEMta#96]
See https://github.com/MoMEMta/MoMEMta/blob/master/modules/Summer.cc#L35

Currently, the counter (or sum) is reset at the beginning of the Looper loop. This works correctly when only one Looper is used, but when nested, the sum is reset too soon.

The reset should happen in `beginIntegration` instead of `beginLoop`.

More over, it'd probably be good to rename the module to something like `LooperSummer`.

**Comment by swertz** [comment]
@blinkseb Have you started working on this? If not I can do it ;)

**Comment by swertz** [comment]
@BrieucF this have to be fixed before you start computing a serious amount of weights...

**Comment by blinkseb** [comment]
Sorry for answering this late, but I was not working on it :)
